# Generated by Django 2.0.2 on 2018-04-01 05:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BocoStock',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number_of_items', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('address_latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('address_longitude', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContacts',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('contact_number', models.PositiveIntegerField()),
                ('poc', models.CharField(max_length=50, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='workorder.Customer')),
            ],
            options={
                'ordering': ['last_modified_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['last_modified_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentRental',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['last_modified_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stock_type', models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')], default='MECHANICAL', max_length=15)),
                ('item_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubContractor',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sub_contractor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.PositiveIntegerField()),
                ('poc', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('address_latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('address_longitude', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['last_modified_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='CREATED', max_length=100)),
                ('work_order_num', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1000)])),
                ('customer_po_num', models.PositiveIntegerField()),
                ('work_order_by', models.CharField(max_length=100)),
                ('date_of_order', models.DateTimeField()),
                ('date_work_started', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('other_requirements', models.CharField(blank=True, max_length=500, null=True)),
                ('has_additional_comments', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='workorder.Customer')),
            ],
            options={
                'ordering': ['last_modified_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkorderEquipment',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workorders', to='workorder.Equipment')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipments', to='workorder.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderEquipmentRental',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('equipment_rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workorders', to='workorder.EquipmentRental')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rentals', to='workorder.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSubContractor',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sub_contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_order', to='workorder.SubContractor')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_contractors', to='workorder.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSuppliers',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workorders', to='workorder.Supplier')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suppliers', to='workorder.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkorderTimeEntry',
            fields=[
                ('deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('work_type', models.CharField(max_length=50)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_entries', to='workorder.WorkOrder')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subcontractor',
            unique_together={('sub_contractor_name', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('stock_type', 'item_name')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('company_name', 'email')},
        ),
        migrations.AddField(
            model_name='bocostock',
            name='stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workorders', to='workorder.Stock'),
        ),
        migrations.AddField(
            model_name='bocostock',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks', to='workorder.WorkOrder'),
        ),
        migrations.AlterUniqueTogether(
            name='workordertimeentry',
            unique_together={('workorder', 'employee_name', 'date', 'work_type')},
        ),
        migrations.AlterUniqueTogether(
            name='workordersuppliers',
            unique_together={('workorder', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='workordersubcontractor',
            unique_together={('sub_contractor', 'work_order')},
        ),
        migrations.AlterUniqueTogether(
            name='workorderequipmentrental',
            unique_together={('workorder', 'equipment_rental')},
        ),
        migrations.AlterUniqueTogether(
            name='workorderequipment',
            unique_together={('workorder', 'equipment')},
        ),
        migrations.AlterUniqueTogether(
            name='bocostock',
            unique_together={('workorder', 'stocks')},
        ),
    ]
