# Generated by Django 2.0.2 on 2018-04-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workordertimeentry',
            unique_together={('workorder', 'date', 'work_type')},
        ),
    ]
