# Generated by Django 2.0.2 on 2018-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20180401_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signature_bs64_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
