# Generated by Django 2.0.2 on 2018-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20180408_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='poc',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
